--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2
-- Dumped by pg_dump version 12.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actors; Type: TABLE; Schema: public; Owner: abagaria
--

CREATE TABLE public.actors (
    id integer NOT NULL,
    name character varying,
    age integer,
    email character varying,
    salary integer
);


ALTER TABLE public.actors OWNER TO abagaria;

--
-- Name: actors_id_seq; Type: SEQUENCE; Schema: public; Owner: abagaria
--

CREATE SEQUENCE public.actors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.actors_id_seq OWNER TO abagaria;

--
-- Name: actors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: abagaria
--

ALTER SEQUENCE public.actors_id_seq OWNED BY public.actors.id;


--
-- Name: movies; Type: TABLE; Schema: public; Owner: abagaria
--

CREATE TABLE public.movies (
    id integer NOT NULL,
    name character varying,
    length double precision,
    genre character varying
);


ALTER TABLE public.movies OWNER TO abagaria;

--
-- Name: movies_id_seq; Type: SEQUENCE; Schema: public; Owner: abagaria
--

CREATE SEQUENCE public.movies_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.movies_id_seq OWNER TO abagaria;

--
-- Name: movies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: abagaria
--

ALTER SEQUENCE public.movies_id_seq OWNED BY public.movies.id;


--
-- Name: actors id; Type: DEFAULT; Schema: public; Owner: abagaria
--

ALTER TABLE ONLY public.actors ALTER COLUMN id SET DEFAULT nextval('public.actors_id_seq'::regclass);


--
-- Name: movies id; Type: DEFAULT; Schema: public; Owner: abagaria
--

ALTER TABLE ONLY public.movies ALTER COLUMN id SET DEFAULT nextval('public.movies_id_seq'::regclass);


--
-- Data for Name: actors; Type: TABLE DATA; Schema: public; Owner: abagaria
--

COPY public.actors (id, name, age, email, salary) FROM stdin;
2	alka	10	alka@alka.com	3000
1	alka	1	abc@alka.com	3000
\.


--
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: abagaria
--

COPY public.movies (id, name, length, genre) FROM stdin;
1	alka_movie	10.5	Action
\.


--
-- Name: actors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: abagaria
--

SELECT pg_catalog.setval('public.actors_id_seq', 2, true);


--
-- Name: movies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: abagaria
--

SELECT pg_catalog.setval('public.movies_id_seq', 1, true);


--
-- Name: actors actors_pkey; Type: CONSTRAINT; Schema: public; Owner: abagaria
--

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_pkey PRIMARY KEY (id);


--
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: abagaria
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

